version: "3"

services:
  db-nodes-and-pools:
    build:
      context: ./db/nodes-and-pools
      args:
        GO_PASSWORD: 98765
        WEB_PASSWORD: 98765
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    container_name: db-nodes-and-pools
    volumes:
      #- db-nodes-and-pools:/var/lib/postgresql/data
      - /home/andrewnk/nodes-and-pools:/var/lib/postgresql/data
    networks:
      - nodes-and-pools-backend

  db-daemon-cache:
    build:
      context: ./db/daemon-cache
      args:
        TURTLECOINSERVICE_PASSWORD: 98765
        WEB_PASSWORD: 98765
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    container_name: db-daemon-cache
    depends_on:
      - daemon
    volumes:
      #- db-daemon-cache:/var/lib/postgresql/data
      - /home/andrewnk/daemon-db:/var/lib/postgresql/data
    networks:
      - daemon-backend

  daemon:
    build:
      context: ./daemon
      args:
        TURTLECOIN_PROGRAM: TurtleCoind
    restart: always
    container_name: daemon
    volumes:
      - /home/andrewnk/daemon:/home/turtlecoin/.TurtleCoin
    networks:
      - daemon-backend

  service-nodes-and-pools:
    build:
      context: ./service/nodes-and-pools
      args:
        DB_USER: go
        DB_NAME: trtl
        DB_PASSWORD: 98765
        DB_HOST: db-nodes-and-pools
        DB_PORT: 5432
        DB_SSLMODE: disable
    container_name: service-nodes-and-pools
    restart: always
    networks:
      - nodes-and-pools-backend
    depends_on:
      - db-nodes-and-pools

  # service-daemon-cache:
  #   build:
  #     context: ./service/daemon-cache
  #     args:
  #       DB_USER: service
  #       DB_NAME: daemon_cache
  #       DB_PASSWORD: 98765
  #       DB_HOST: db-daemon-cache
  #       DB_PORT: 5432
  #       DAEMON_RPC_PORT: 11898
  #       DAEMON_RPC_HOST: daemon
  #   restart: always
  #   container_name: service-daemon-cache
  #   depends_on: 
  #     - db-daemon-cache
  #   networks:
  #     - daemon-backend

  web-backend:
    build:
      context: ./web/backend
      args:
        DB_USER: web
        DB_PASSWORD: 98765
        DB_PORT: 5432
        DB_HOST: db-nodes-and-pools
        DB_NAME: trtl
    restart: always
    container_name: web-backend
    depends_on:
      - db-nodes-and-pools
      - service-nodes-and-pools
      # - db-daemon-cache
    ports:
      - 8080:3030
    networks:
      - nodes-and-pools-backend
      - daemon-backend
      - web-backend
      - web-frontend

  web-frontend:
    build:
      context: ./web/frontend
      args:
        WEBSOCKET_HOST: localhost
        WEBSOCKET_PORT: 8080
    restart: always
    container_name: web-frontend
    networks:
      - web-frontend
    depends_on:
      - db-nodes-and-pools
      - service-nodes-and-pools
      # - db-daemon-cache
      - web-backend
    ports:
      - 80:3000

  web-cache:
    image: redis:alpine
    container_name: web-cache
    depends_on:
      - web-backend
    restart: always
    networks:
      - web-backend

networks:
  nodes-and-pools-backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16

  daemon-backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16

  web-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16

  web-backend:
    driver: bridge
    ipam:
      driver: default

# volumes:
#   db-nodes-and-pools: